name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    
    # GitHub Secretsを使用
    env:
      POSTGRES_USER: ${{ secrets.TEST_POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.TEST_POSTGRES_PASSWORD }}
      POSTGRES_SERVER: ${{ secrets.TEST_POSTGRES_SERVER }}
      POSTGRES_PORT: ${{ secrets.TEST_POSTGRES_PORT }}
      POSTGRES_DB: ${{ secrets.TEST_POSTGRES_DB }}
    
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      
      # Python環境とuv環境の同期を追加
      - name: Set up the environment
        run: uv sync --frozen

      - name: Format
        run: uvx ruff format . --check --diff

      - name: Lint
        run: uvx ruff check --output-format=github .

      - name: Test
        run: uv run --frozen pytest